name: Build and Test Serenity Project

on:
  push:
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-latest


    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Checking Sonar Action
        uses: actions/checkout@v2
        with:
                repository: alejandro9212/repositori_test_prueba
                ref: ""
                token: ${{ secrets.DIG_READER_GITHUB_ACCESS_TOKEN }}
                persist-credentials: false
                path: ./.github/actions/test-integration



      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Install dependencies and run tests
        run: mvn clean verify -DskipTests
      - name: Ejecutar pruebas con Serenity
        run: mvn clean verify -Dtags="type:regression"

      - name: Guardar reportes
        uses: actions/upload-artifact@v4
        with:
          name: extent-reports
          path: target/reports/ApisReporte.html
