name: Build and Test Serenity Project

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Close Chrome processes
        run: pkill -f chrome || true

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Checking Sonar Action
        uses: actions/checkout@v2
        with:
          repository: alejandro9212/repositori_test_prueba
          ref: ""
          token: ${{ secrets.DIG_READER_GITHUB_ACCESS_TOKEN }}
          persist-credentials: false
          path: ./.github/actions/test-integration

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Google Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Ejecutar pruebas con Serenity
        run: mvn clean verify -Dtags="@regression"

      - name: Guardar reportes
        uses: actions/upload-artifact@v4
        with:
          name: serenity-reports
          path: target/site/serenity/5df6b1f9b15439d52ca6b16355cc375fce9dbf4c5a2f1c4d395e69e7decef44c

