name: automated-testing-integration

on:
  push:
    branches:
      - staging
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup environment
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          architecture: x64
          distribution: "adopt"
      - name: Restore cache
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Install Dependencies
        shell: bash
        run: mvn verify -Dtest=TestRunner


  integration-e2e-test:
    runs-on: ubuntu-latest
    needs:
      - build
    environment: agregue el nombre de su environment de Github, si no lo usa borre esta linea
    env:
      BROWSERSTACK_KEY: ${{ secrets.BROWSERSTACK_KEY }}
      BROWSERSTACK_USER: ${{ secrets.BROWSERSTACK_USER }}
      TESTLINK_KEY: ${{ secrets.TESTLINK_KEY }}
    steps:
      - uses: actions/checkout@v2
      - name: Restore cache
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14.x
      - name: Run testing
        shell: bash
        run: |
          bash ./pipeline/run-end2end.sh
      - name: Upload reports
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: reports
          retention-days: 30
          path: |
            agregua aqui la ruta de los archivos que quieres exportar