name: Build and Test Serenity Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Install dependencies and run tests
        run: mvn clean verify
      - name: 🔥Ejecutar pruebas con Serenity
        run: mvn clean verify -Dtest=ApisTest

      - name: 📂 Guardar reportes
        uses: actions/upload-artifact@v4
        with:
          name: extent-reports
          path: target/reports/ApisReporte.html
